[package]
name = "ferrules"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tracing = "0.1.41"
clap = { version = "4.5.23", features = ["derive"] }
pdfium-render = { version = "0.8.27", features = ["static"] }
image = "0.25.5"
# Inference
ndarray = "0.16.1"
ort = { version = "=2.0.0-rc.9", features = ["coreml", "fetch-models"] }
plsfix = "0.1.7"
lazy_static = "1.5.0"
imageproc = "0.25.0"
ab_glyph = "0.2.29"
uuid = { version = "1.11.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
rand = "0.8.5"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "^0.5.2" }
objc2-foundation = { version = "^0.2.2" }
objc2-vision = { version = "^0.2.2", features = [
    "VNRequest",
    "VNRequestHandler",
    "VNRecognizeTextRequest",
    # Getting results
    "VNObservation",
    "VNTypes",
] }


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "layout"
harness = false

[profile.release]
debug = 1
